### PR TITLE
Refs #10299 - implemented new Node API

### PR DESCRIPTION
**Pull request by lzap**
Do not merge just like that. This needs to be tested with huge patch
https://github.com/theforeman/foreman-discovery-image/pull/21

### CODE REVIEW

**Comment by lzap** [comment]
[test]

**Comment by lzap** [comment]
@stbenjam added missing tests, this was the last bit!

**Comment by stbenjam** [comment]
Can this wait until next week? I want to be able to test it with the proxy, so far I only tried with the Foreman itself.

**Comment by lzap** [comment]
> Can this wait until next week? I want to be able to test it with the proxy, so far I only tried with the Foreman itself.

I think so, Sachin can start testing without proxy for now.

Thanks!

## 

Later,
 Lukas #lzap Zapletal

**Comment by stbenjam** [comment]
Merged as 80c18f7836c5de7b6b298d82e92f4d9468898848, thanks @lzap

**Pull request closed without merging**
