### PR TITLE
Add packit config

### PR DESCRIPTION
**Pull request by nofaralfasi**

### CODE REVIEW

**Comment by nofaralfasi** [comment]
@evgeni It seems to be the same error we encountered here: https://github.com/theforeman/hammer-cli-foreman-discovery/pull/56. I tried to run `./add_gem_package.sh smart_proxy_discovery smart_proxy_plugin plugins` and got the following output:
```
Detected update...
rm 'packages/plugins/rubygem-smart_proxy_discovery/rubygem-smart_proxy_discovery.spec'
rm 'packages/plugins/rubygem-smart_proxy_discovery/smart_proxy_discovery-1.0.5.gem'
~/git/foreman-packaging/packages/plugins/rubygem-smart_proxy_discovery ~/git/foreman-packaging
rbenv: gem2rpm: command not found

The `gem2rpm' command exists in these Ruby versions:
  2.7.2
```
Am I missing something? I'm using Ruby 3.0. Should I temporarily switch Ruby versions?

**Comment by evgeni** [comment]
> Am I missing something? I'm using Ruby 3.0. Should I temporarily switch Ruby versions?

You're missing `gem2rpm`, which you either need to install for 3.0 or switch Rubies, yes.

**Comment by nofaralfasi** [comment]
Opened https://github.com/theforeman/foreman-packaging/pull/10534 to fix the failing tests.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
