### PR TITLE
test jenkins pull-request

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by lzap** [comment]
How to make a test PR - locate README, find a grammar error, profit! Shame on me :man_facepalming: 

Ok it's done but it says "No test results found."

**Comment by evgeni** [comment]
[test smart_proxy_discovery]

**Comment by evgeni** [comment]
hah, this needs to be rebased on latest `develop` to pass tests.

**Comment by lzap** [comment]
We are nearing a release, let me do it.

**Pull request merged**
